[package]
name = "Installer"
version = "0.1.0"
edition = "2024"

[dependencies]
"sha2" = "0.10.9"
"bytes" = "1.11.0"
"serde_json" = "1.0.149"
"reqwest" = { version="0.13.1", features = ["blocking", "json", "multipart"]}
"base16ct" = { version = "1.0.0", features = ["alloc"]}